# Note: 7/21/2026
# Note: currently the vtk file generated by this approach does not have the correct nodal data for displacement and potential (voltage), but it has correct info about element type, material type, etc.

# Note: Using EnSight to open .rst file and export a case file with user selected field quantities (scalars, vectors, etc) can provide the correct nodal and element data, which can then be read into ParaView for visualization.

from ansys.mapdl import reader as pymapdl_reader
result = pymapdl_reader.read_binary("C:/Workspace/MAPDL/PiezoresistiveAnalysis.rst")
result.save_as_vtk("C:/Workspace/MAPDL/PiezoresistiveAnalysis.vtk")